# The following file contains the configuration for the 
#  ReportMancer application. To apply the configuration,
#  make sure to restart the application

# For booleans use True and False, 
#  anything else may result in unpredictable behavior

[Auth]
require_auth = True

[Export]
download_available = True

export_active = True
export_to = ["192.168.10.55"]
